<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="5" ignored="0" total="5" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="73667" started-at="2019-11-04T09:42:45Z" finished-at="2019-11-04T09:43:59Z">
    <groups>
      <group name="SmokeTesting">
        <method signature="VerifyingDuplicateWithAnnualREvenue.AnnualRevenueTest()[pri:0, instance:com.crm.OrganisationTest.VerifyingDuplicateWithAnnualREvenue@1e88b3c]" name="AnnualRevenueTest" class="com.crm.OrganisationTest.VerifyingDuplicateWithAnnualREvenue"/>
      </group> <!-- SmokeTesting -->
      <group name="RegressionTesting">
        <method signature="VerifyingDuplicateWithAnnualREvenue.AsignedToTest()[pri:0, instance:com.crm.OrganisationTest.VerifyingDuplicateWithAnnualREvenue@1e88b3c]" name="AsignedToTest" class="com.crm.OrganisationTest.VerifyingDuplicateWithAnnualREvenue"/>
        <method signature="VerifyingDuplicateWithAnnualREvenue.BillingAddressTest()[pri:0, instance:com.crm.OrganisationTest.VerifyingDuplicateWithAnnualREvenue@1e88b3c]" name="BillingAddressTest" class="com.crm.OrganisationTest.VerifyingDuplicateWithAnnualREvenue"/>
        <method signature="VerifyingDuplicateWithAnnualREvenue.EmployesTest()[pri:0, instance:com.crm.OrganisationTest.VerifyingDuplicateWithAnnualREvenue@1e88b3c]" name="EmployesTest" class="com.crm.OrganisationTest.VerifyingDuplicateWithAnnualREvenue"/>
        <method signature="VerifyingDuplicateWithAnnualREvenue.IndustryTest()[pri:0, instance:com.crm.OrganisationTest.VerifyingDuplicateWithAnnualREvenue@1e88b3c]" name="IndustryTest" class="com.crm.OrganisationTest.VerifyingDuplicateWithAnnualREvenue"/>
      </group> <!-- RegressionTesting -->
    </groups>
    <test name="Default test" duration-ms="73667" started-at="2019-11-04T09:42:45Z" finished-at="2019-11-04T09:43:59Z">
      <class name="com.crm.OrganisationTest.VerifyingDuplicateWithAnnualREvenue">
        <test-method status="PASS" signature="configBC()[pri:0, instance:com.crm.OrganisationTest.VerifyingDuplicateWithAnnualREvenue@1e88b3c]" name="configBC" is-config="true" duration-ms="6325" started-at="2019-11-04T09:42:45Z" finished-at="2019-11-04T09:42:51Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- configBC -->
        <test-method status="PASS" signature="configBM()[pri:0, instance:com.crm.OrganisationTest.VerifyingDuplicateWithAnnualREvenue@1e88b3c]" name="configBM" is-config="true" duration-ms="13740" started-at="2019-11-04T09:42:51Z" finished-at="2019-11-04T09:43:05Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- configBM -->
        <test-method status="FAIL" signature="AnnualRevenueTest()[pri:0, instance:com.crm.OrganisationTest.VerifyingDuplicateWithAnnualREvenue@1e88b3c]" name="AnnualRevenueTest" duration-ms="28" started-at="2019-11-04T09:43:05Z" finished-at="2019-11-04T09:43:05Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [vtigerCRM5-CommercialOpenSourceCRM] but found [Administrator-Home-vtigerCRM5-CommercialOpenSourceCRM]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [vtigerCRM5-CommercialOpenSourceCRM] but found [Administrator-Home-vtigerCRM5-CommercialOpenSourceCRM]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at com.crm.OrganisationTest.VerifyingDuplicateWithAnnualREvenue.AnnualRevenueTest(VerifyingDuplicateWithAnnualREvenue.java:33)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- AnnualRevenueTest -->
        <test-method status="PASS" signature="configAfterMethod()[pri:0, instance:com.crm.OrganisationTest.VerifyingDuplicateWithAnnualREvenue@1e88b3c]" name="configAfterMethod" is-config="true" duration-ms="5117" started-at="2019-11-04T09:43:05Z" finished-at="2019-11-04T09:43:10Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- configAfterMethod -->
        <test-method status="PASS" signature="configBM()[pri:0, instance:com.crm.OrganisationTest.VerifyingDuplicateWithAnnualREvenue@1e88b3c]" name="configBM" is-config="true" duration-ms="4529" started-at="2019-11-04T09:43:10Z" finished-at="2019-11-04T09:43:15Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- configBM -->
        <test-method status="FAIL" signature="AsignedToTest()[pri:0, instance:com.crm.OrganisationTest.VerifyingDuplicateWithAnnualREvenue@1e88b3c]" name="AsignedToTest" duration-ms="154" started-at="2019-11-04T09:43:15Z" finished-at="2019-11-04T09:43:15Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [vtigerCRM5-CommercialOpenSourceCRM] but found [Administrator-Home-vtigerCRM5-CommercialOpenSourceCRM]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [vtigerCRM5-CommercialOpenSourceCRM] but found [Administrator-Home-vtigerCRM5-CommercialOpenSourceCRM]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at com.crm.OrganisationTest.VerifyingDuplicateWithAnnualREvenue.AsignedToTest(VerifyingDuplicateWithAnnualREvenue.java:142)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- AsignedToTest -->
        <test-method status="PASS" signature="configAfterMethod()[pri:0, instance:com.crm.OrganisationTest.VerifyingDuplicateWithAnnualREvenue@1e88b3c]" name="configAfterMethod" is-config="true" duration-ms="7118" started-at="2019-11-04T09:43:15Z" finished-at="2019-11-04T09:43:22Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- configAfterMethod -->
        <test-method status="PASS" signature="configBM()[pri:0, instance:com.crm.OrganisationTest.VerifyingDuplicateWithAnnualREvenue@1e88b3c]" name="configBM" is-config="true" duration-ms="5005" started-at="2019-11-04T09:43:22Z" finished-at="2019-11-04T09:43:27Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- configBM -->
        <test-method status="FAIL" signature="BillingAddressTest()[pri:0, instance:com.crm.OrganisationTest.VerifyingDuplicateWithAnnualREvenue@1e88b3c]" name="BillingAddressTest" duration-ms="87" started-at="2019-11-04T09:43:27Z" finished-at="2019-11-04T09:43:27Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [vtigerCRM5-CommercialOpenSourceCRM] but found [Administrator-Home-vtigerCRM5-CommercialOpenSourceCRM]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [vtigerCRM5-CommercialOpenSourceCRM] but found [Administrator-Home-vtigerCRM5-CommercialOpenSourceCRM]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at com.crm.OrganisationTest.VerifyingDuplicateWithAnnualREvenue.BillingAddressTest(VerifyingDuplicateWithAnnualREvenue.java:249)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- BillingAddressTest -->
        <test-method status="PASS" signature="configAfterMethod()[pri:0, instance:com.crm.OrganisationTest.VerifyingDuplicateWithAnnualREvenue@1e88b3c]" name="configAfterMethod" is-config="true" duration-ms="6849" started-at="2019-11-04T09:43:27Z" finished-at="2019-11-04T09:43:34Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- configAfterMethod -->
        <test-method status="PASS" signature="configBM()[pri:0, instance:com.crm.OrganisationTest.VerifyingDuplicateWithAnnualREvenue@1e88b3c]" name="configBM" is-config="true" duration-ms="6528" started-at="2019-11-04T09:43:34Z" finished-at="2019-11-04T09:43:41Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- configBM -->
        <test-method status="FAIL" signature="EmployesTest()[pri:0, instance:com.crm.OrganisationTest.VerifyingDuplicateWithAnnualREvenue@1e88b3c]" name="EmployesTest" duration-ms="9" started-at="2019-11-04T09:43:41Z" finished-at="2019-11-04T09:43:41Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [vtigerCRM5-CommercialOpenSourceCRM] but found [Administrator-Home-vtigerCRM5-CommercialOpenSourceCRM]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [vtigerCRM5-CommercialOpenSourceCRM] but found [Administrator-Home-vtigerCRM5-CommercialOpenSourceCRM]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at com.crm.OrganisationTest.VerifyingDuplicateWithAnnualREvenue.EmployesTest(VerifyingDuplicateWithAnnualREvenue.java:356)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- EmployesTest -->
        <test-method status="PASS" signature="configAfterMethod()[pri:0, instance:com.crm.OrganisationTest.VerifyingDuplicateWithAnnualREvenue@1e88b3c]" name="configAfterMethod" is-config="true" duration-ms="5359" started-at="2019-11-04T09:43:41Z" finished-at="2019-11-04T09:43:46Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- configAfterMethod -->
        <test-method status="PASS" signature="configBM()[pri:0, instance:com.crm.OrganisationTest.VerifyingDuplicateWithAnnualREvenue@1e88b3c]" name="configBM" is-config="true" duration-ms="4540" started-at="2019-11-04T09:43:46Z" finished-at="2019-11-04T09:43:50Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- configBM -->
        <test-method status="FAIL" signature="IndustryTest()[pri:0, instance:com.crm.OrganisationTest.VerifyingDuplicateWithAnnualREvenue@1e88b3c]" name="IndustryTest" duration-ms="137" started-at="2019-11-04T09:43:50Z" finished-at="2019-11-04T09:43:51Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [vtigerCRM5-CommercialOpenSourceCRM] but found [Administrator-Home-vtigerCRM5-CommercialOpenSourceCRM]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [vtigerCRM5-CommercialOpenSourceCRM] but found [Administrator-Home-vtigerCRM5-CommercialOpenSourceCRM]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at com.crm.OrganisationTest.VerifyingDuplicateWithAnnualREvenue.IndustryTest(VerifyingDuplicateWithAnnualREvenue.java:462)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- IndustryTest -->
        <test-method status="PASS" signature="configAfterMethod()[pri:0, instance:com.crm.OrganisationTest.VerifyingDuplicateWithAnnualREvenue@1e88b3c]" name="configAfterMethod" is-config="true" duration-ms="7439" started-at="2019-11-04T09:43:51Z" finished-at="2019-11-04T09:43:58Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- configAfterMethod -->
        <test-method status="PASS" signature="configAfterClass()[pri:0, instance:com.crm.OrganisationTest.VerifyingDuplicateWithAnnualREvenue@1e88b3c]" name="configAfterClass" is-config="true" duration-ms="666" started-at="2019-11-04T09:43:58Z" finished-at="2019-11-04T09:43:59Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- configAfterClass -->
      </class> <!-- com.crm.OrganisationTest.VerifyingDuplicateWithAnnualREvenue -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
